// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BsModalController from "./bs_modal_controller"
application.register("bs-modal", BsModalController)

import CountriesController from "./countries_controller"
application.register("countries", CountriesController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserModalController from "./user_modal_controller"
application.register("user-modal", UserModalController)
